// XGC Gazebo Classic camera source.
//
// The normal frame path intentionally never enters ROS or system memory:
//   OGRE render texture -> OpenGL RGBA texture -> NVENC H264 -> loopback RTP.
// A CPU RGB/JPEG readback exists only for an explicit calibration snapshot
// transaction received over a private Unix-domain socket.

#include <gazebo/common/Console.hh>
#include <gazebo/common/Events.hh>
#include <gazebo/common/Plugin.hh>
#include <gazebo/gazebo.hh>
#include <gazebo/rendering/Camera.hh>
#include <gazebo/sensors/CameraSensor.hh>

#include <OgreHardwarePixelBuffer.h>
#include <OgrePixelFormat.h>
#include <OgreRenderTarget.h>
#include <OgreTexture.h>
#include <RenderSystems/GL/OgreGLTexture.h>

#ifndef GL_GLEXT_PROTOTYPES
#define GL_GLEXT_PROTOTYPES 1
#endif
#include <GL/gl.h>
#include <GL/glext.h>

#include <jpeglib.h>
#include <ffnvcodec/nvEncodeAPI.h>

#include <arpa/inet.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/un.h>
#include <unistd.h>

#include <algorithm>
#include <array>
#include <atomic>
#include <cerrno>
#include <csetjmp>
#include <chrono>
#include <cmath>
#include <condition_variable>
#include <cstdint>
#include <cstdio>
#include <cstring>
#include <dlfcn.h>
#include <deque>
#include <filesystem>
#include <functional>
#include <limits>
#include <memory>
#include <mutex>
#include <optional>
#include <sstream>
#include <string>
#include <system_error>
#include <thread>
#include <utility>
#include <vector>

namespace gazebo {
namespace {

constexpr std::size_t kMaximumControlRequestBytes = 64 * 1024;
constexpr std::size_t kMaximumRtpPayloadBytes = 1'200;
constexpr std::size_t kMinimumPacedQueueBytes = 256 * 1024;
constexpr std::uint8_t kH264PayloadType = 96;
constexpr std::uint32_t kRtpSSRC = 0x58474332;  // "XGC2"

using NvEncodeAPICreateInstance = NVENCSTATUS (NVENCAPI *)(NV_ENCODE_API_FUNCTION_LIST *);

struct JPEGErrorManager {
  jpeg_error_mgr manager;
  jmp_buf jumpBuffer;
};

extern "C" void JPEGErrorExit(j_common_ptr info) {
  auto *error = reinterpret_cast<JPEGErrorManager *>(info->err);
  longjmp(error->jumpBuffer, 1);
}

template <typename Value>
Value SDFValue(const sdf::ElementPtr &sdf, const std::string &name, Value fallback) {
  if (sdf && sdf->HasElement(name)) {
    return sdf->Get<Value>(name);
  }
  return fallback;
}

bool IsSafeIdentifier(const std::string &value) {
  if (value.empty() || value.size() > 128) {
    return false;
  }
  return std::all_of(value.begin(), value.end(), [](unsigned char character) {
    return std::isalnum(character) || character == '-' || character == '_' || character == '.';
  });
}

std::string EscapeJSON(const std::string &value) {
  std::ostringstream escaped;
  for (unsigned char character : value) {
    switch (character) {
      case '"': escaped << "\\\""; break;
      case '\\': escaped << "\\\\"; break;
      case '\b': escaped << "\\b"; break;
      case '\f': escaped << "\\f"; break;
      case '\n': escaped << "\\n"; break;
      case '\r': escaped << "\\r"; break;
      case '\t': escaped << "\\t"; break;
      default:
        if (character < 0x20) {
          escaped << "\\u00" << std::hex << static_cast<unsigned int>(character) << std::dec;
        } else {
          escaped << character;
        }
    }
  }
  return escaped.str();
}

std::optional<std::string> JSONString(const std::string &document, const std::string &name) {
  const std::string key = "\"" + name + "\"";
  const std::size_t keyPosition = document.find(key);
  if (keyPosition == std::string::npos) {
    return std::nullopt;
  }
  std::size_t cursor = document.find(':', keyPosition + key.size());
  if (cursor == std::string::npos) {
    return std::nullopt;
  }
  ++cursor;
  while (cursor < document.size() && std::isspace(static_cast<unsigned char>(document[cursor]))) {
    ++cursor;
  }
  if (cursor >= document.size() || document[cursor] != '"') {
    return std::nullopt;
  }
  ++cursor;
  std::string value;
  bool escaped = false;
  for (; cursor < document.size(); ++cursor) {
    const char character = document[cursor];
    if (escaped) {
      // Source-control values are generated by XGC and use only identifiers.
      // Preserve the escaped byte rather than accepting a second JSON grammar.
      value.push_back(character);
      escaped = false;
      continue;
    }
    if (character == '\\') {
      escaped = true;
      continue;
    }
    if (character == '"') {
      return value;
    }
    value.push_back(character);
  }
  return std::nullopt;
}

std::optional<bool> JSONBoolean(const std::string &document, const std::string &name) {
  const std::string key = "\"" + name + "\"";
  const std::size_t keyPosition = document.find(key);
  if (keyPosition == std::string::npos) {
    return std::nullopt;
  }
  std::size_t cursor = document.find(':', keyPosition + key.size());
  if (cursor == std::string::npos) {
    return std::nullopt;
  }
  ++cursor;
  while (cursor < document.size() && std::isspace(static_cast<unsigned char>(document[cursor]))) {
    ++cursor;
  }
  if (document.compare(cursor, 4, "true") == 0) {
    return true;
  }
  if (document.compare(cursor, 5, "false") == 0) {
    return false;
  }
  return std::nullopt;
}

bool SendAll(int descriptor, const void *data, std::size_t size) {
  const auto *cursor = static_cast<const std::uint8_t *>(data);
  while (size > 0) {
    const ssize_t sent = send(descriptor, cursor, size, MSG_NOSIGNAL);
    if (sent < 0) {
      if (errno == EINTR) {
        continue;
      }
      return false;
    }
    if (sent == 0) {
      return false;
    }
    cursor += sent;
    size -= static_cast<std::size_t>(sent);
  }
  return true;
}

std::optional<std::string> ReadControlLine(int descriptor) {
  std::string line;
  line.reserve(512);
  while (line.size() <= kMaximumControlRequestBytes) {
    char character = 0;
    const ssize_t received = recv(descriptor, &character, 1, 0);
    if (received == 0) {
      return std::nullopt;
    }
    if (received < 0) {
      if (errno == EINTR) {
        continue;
      }
      return std::nullopt;
    }
    if (character == '\n') {
      return line;
    }
    line.push_back(character);
  }
  return std::nullopt;
}

std::vector<std::vector<std::uint8_t>> SplitAnnexB(const std::uint8_t *data, std::size_t size) {
  auto startCodeLength = [data, size](std::size_t offset) -> std::size_t {
    if (offset + 3 <= size && data[offset] == 0 && data[offset + 1] == 0 && data[offset + 2] == 1) {
      return 3;
    }
    if (offset + 4 <= size && data[offset] == 0 && data[offset + 1] == 0 && data[offset + 2] == 0 && data[offset + 3] == 1) {
      return 4;
    }
    return 0;
  };

  std::vector<std::vector<std::uint8_t>> nalUnits;
  std::size_t start = 0;
  while (start < size && startCodeLength(start) == 0) {
    ++start;
  }
  while (start < size) {
    const std::size_t prefix = startCodeLength(start);
    if (prefix == 0) {
      break;
    }
    const std::size_t payloadStart = start + prefix;
    std::size_t next = payloadStart;
    while (next < size && startCodeLength(next) == 0) {
      ++next;
    }
    if (next > payloadStart) {
      nalUnits.emplace_back(data + payloadStart, data + next);
    }
    start = next;
  }
  return nalUnits;
}

}  // namespace

class XGCMediaCameraPlugin final : public SensorPlugin, private Ogre::RenderTargetListener {
 public:
  XGCMediaCameraPlugin() = default;

  ~XGCMediaCameraPlugin() override {
    stopping_.store(true);
    postRenderConnection_.reset();
    if (renderTarget_) {
      renderTarget_->removeListener(this);
      renderTarget_ = nullptr;
    }
    StopControlServer();
    StopRTPPacer();
    if (rtpSocket_ >= 0) {
      close(rtpSocket_);
      rtpSocket_ = -1;
    }
    // GL/NVENC resources are intentionally released from OnPostRender while a
    // valid Gazebo render context is current. Process exit owns any final
    // teardown that occurs after Gazebo has removed that context.
  }

  void Load(sensors::SensorPtr parent, sdf::ElementPtr sdf) override {
    sensor_ = std::dynamic_pointer_cast<sensors::CameraSensor>(parent);
    if (!sensor_) {
      gzerr << "xgc_media_camera requires a Gazebo CameraSensor\n";
      return;
    }

    sourceID_ = SDFValue<std::string>(sdf, "sourceId", "usb_cam");
    frameID_ = SDFValue<std::string>(sdf, "frameId", "usb_cam_optical_frame");
    rtpHost_ = SDFValue<std::string>(sdf, "rtpHost", "127.0.0.1");
    rtpPort_ = SDFValue<int>(sdf, "rtpPort", 5004);
    controlSocketPath_ = SDFValue<std::string>(sdf, "controlSocket", "/tmp/xgc2/media/usb_cam.sock");
    bitrate_ = SDFValue<int>(sdf, "bitrate", 6'000'000);
    maxBitrate_ = SDFValue<int>(sdf, "maxBitrate", bitrate_ + bitrate_ / 2);
    pacingBitrate_ = SDFValue<int>(sdf, "pacingBitrate", maxBitrate_);
    vbvBufferMilliseconds_ = std::clamp(SDFValue<int>(sdf, "vbvBufferMilliseconds", 500), 50, 2'000);
    jpegQuality_ = std::clamp(SDFValue<int>(sdf, "jpegQuality", 90), 50, 100);

    if (!IsSafeIdentifier(sourceID_) || frameID_.empty() || rtpPort_ < 1 || rtpPort_ > 65535 ||
        (rtpHost_ != "127.0.0.1" && rtpHost_ != "localhost") ||
        controlSocketPath_.rfind("/tmp/xgc2/media/", 0) != 0 || bitrate_ < 128'000) {
      gzerr << "xgc_media_camera has invalid private media source configuration\n";
      return;
    }
    if (maxBitrate_ < bitrate_ || pacingBitrate_ < maxBitrate_) {
      gzerr << "xgc_media_camera requires bitrate <= maxBitrate <= pacingBitrate\n";
      return;
    }

    sockaddr_in destination{};
    destination.sin_family = AF_INET;
    destination.sin_port = htons(static_cast<std::uint16_t>(rtpPort_));
    if (inet_pton(AF_INET, "127.0.0.1", &destination.sin_addr) != 1) {
      gzerr << "xgc_media_camera could not resolve loopback RTP target\n";
      return;
    }
    rtpSocket_ = socket(AF_INET, SOCK_DGRAM | SOCK_CLOEXEC, 0);
    if (rtpSocket_ < 0) {
      gzerr << "xgc_media_camera could not create RTP socket: " << std::strerror(errno) << "\n";
      return;
    }
    rtpDestination_ = destination;

    if (!StartRTPPacer()) {
      close(rtpSocket_);
      rtpSocket_ = -1;
      return;
    }

    if (!StartControlServer()) {
      StopRTPPacer();
      close(rtpSocket_);
      rtpSocket_ = -1;
      return;
    }

    // Render only on demand. The global post-render callback remains available
    // to turn a camera back on for a new WebRTC consumer or one snapshot.
    sensor_->SetActive(false);
    postRenderConnection_ = event::Events::ConnectPostRender(
        std::bind(&XGCMediaCameraPlugin::OnPostRender, this));
    gzmsg << "xgc_media_camera source " << sourceID_ << " serves H264/RTP through 127.0.0.1:" << rtpPort_ << "\n";
  }

 private:
  struct SnapshotResult {
    bool completed = false;
    bool failed = false;
    std::string error;
    std::string id;
    std::int64_t timestampNanoseconds = 0;
    unsigned int width = 0;
    unsigned int height = 0;
    std::array<double, 9> cameraMatrix{};
    std::array<double, 5> distortion{};
    std::vector<std::uint8_t> rgb;
    std::vector<std::uint8_t> jpeg;
  };

  struct QueuedRTPPacket {
    std::vector<std::uint8_t> bytes;
  };

  struct QueuedRTPAccessUnit {
    std::vector<QueuedRTPPacket> packets;
    std::size_t bytes = 0;
    std::uint64_t generation = 0;
    std::chrono::nanoseconds framePeriod{};
  };

  // NVENC exposes an encoded access unit all at once. Sending all of its RTP
  // fragments synchronously from the render callback creates a microburst:
  // one 4K IDR frame can exceed the host UDP receive buffer before Media Edge
  // is scheduled. The pacer owns whole access units on a separate thread,
  // transmits them in bounded packet batches, and starts each AU immediately.
  // An IDR is allowed to borrow enough burst bandwidth to finish inside one
  // frame period; carrying its late completion phase into following delta
  // frames would turn normal scheduler jitter into a visible stall.
  bool StartRTPPacer() {
    try {
      rtpPacerStopping_ = false;
      rtpPacerThread_ = std::thread(&XGCMediaCameraPlugin::RTPPacerLoop, this);
      return true;
    } catch (const std::system_error &error) {
      gzerr << "xgc_media_camera could not start RTP pacer: " << error.what() << "\n";
      return false;
    }
  }

  void StopRTPPacer() {
    {
      std::lock_guard<std::mutex> lock(rtpPacerMutex_);
      rtpPacerStopping_ = true;
      rtpQueue_.clear();
      rtpQueuedBytes_ = 0;
      ++rtpQueueGeneration_;
    }
    rtpPacerCondition_.notify_all();
    if (rtpPacerThread_.joinable()) {
      rtpPacerThread_.join();
    }
  }

  void ClearRTPQueue() {
    {
      std::lock_guard<std::mutex> lock(rtpPacerMutex_);
      rtpQueue_.clear();
      rtpQueuedBytes_ = 0;
      ++rtpQueueGeneration_;
    }
    rtpPacerCondition_.notify_all();
  }

  std::size_t MaximumPacedAccessUnitBytes() const {
    // This is a defensive bound for one encoded frame, not permission to
    // accumulate seconds of media. Live viewing keeps only one pending AU.
    return std::max(kMinimumPacedQueueBytes, static_cast<std::size_t>(pacingBitrate_ / 8));
  }

  bool EnqueueRTPAccessUnit(std::vector<QueuedRTPPacket> packets, bool keyframe) {
    if (packets.empty()) {
      return false;
    }
    std::size_t bytes = 0;
    for (const auto &packet : packets) {
      bytes += packet.bytes.size();
    }
    {
      std::lock_guard<std::mutex> lock(rtpPacerMutex_);
      if (rtpPacerStopping_) {
        return false;
      }
      const std::size_t maximum = MaximumPacedAccessUnitBytes();
      if (keyframe && !rtpQueue_.empty()) {
        // An IDR is independently decodable, so it always replaces a stale
        // not-yet-sent delta frame.
        rtpQueue_.clear();
        rtpQueuedBytes_ = 0;
        ++rtpQueueGeneration_;
      }
      if (!keyframe && !rtpQueue_.empty()) {
        // P-frames form a reference chain: sending only the newer queued
        // delta would not produce a latest *decodable* frame. Discard the
        // stale pending chain and make the next capture an IDR instead.
        rtpQueue_.clear();
        rtpQueuedBytes_ = 0;
        ++rtpQueueGeneration_;
        forceKeyframe_.store(true);
        LogEncoderError("live RTP fell behind; replacing stale deltas with a fresh IDR");
        return false;
      }
      if (!keyframe && bytes > maximum) {
        forceKeyframe_.store(true);
        LogEncoderError("delta frame exceeds the RTP latency budget; requesting an IDR");
        return false;
      }
      if (keyframe && bytes > maximum) {
        LogEncoderError("IDR frame exceeds the paced RTP latency budget");
      }
      QueuedRTPAccessUnit accessUnit;
      accessUnit.packets = std::move(packets);
      accessUnit.bytes = bytes;
      accessUnit.generation = rtpQueueGeneration_;
      const double fps = std::max(0.1, static_cast<double>(sensor_->UpdateRate()));
      accessUnit.framePeriod = std::chrono::nanoseconds(std::max<std::int64_t>(
          1, static_cast<std::int64_t>(std::llround(1'000'000'000.0 / fps))));
      rtpQueuedBytes_ += bytes;
      rtpQueue_.push_back(std::move(accessUnit));
    }
    rtpPacerCondition_.notify_one();
    return true;
  }

  std::chrono::nanoseconds RTPAccessUnitSpread(const QueuedRTPAccessUnit &accessUnit) const {
    const double seconds = static_cast<double>(accessUnit.bytes) * 8.0 /
                           static_cast<double>(pacingBitrate_);
    const auto configured = std::chrono::nanoseconds(std::max<std::int64_t>(
        1, static_cast<std::int64_t>(std::ceil(seconds * 1'000'000'000.0))));
    const auto guard = std::min(
        std::chrono::duration_cast<std::chrono::nanoseconds>(std::chrono::milliseconds(4)),
        accessUnit.framePeriod / 4);
    const auto frameBudget = std::max(std::chrono::nanoseconds(1), accessUnit.framePeriod - guard);
    return std::min(configured, frameBudget);
  }

  void RTPPacerLoop() {
    while (true) {
      QueuedRTPAccessUnit accessUnit;
      std::chrono::nanoseconds spread{};
      {
        std::unique_lock<std::mutex> lock(rtpPacerMutex_);
        rtpPacerCondition_.wait(lock, [this] { return rtpPacerStopping_ || !rtpQueue_.empty(); });
        if (rtpPacerStopping_) {
          return;
        }
        accessUnit = std::move(rtpQueue_.front());
        rtpQueue_.pop_front();
        rtpQueuedBytes_ -= accessUnit.bytes;
        spread = RTPAccessUnitSpread(accessUnit);
      }
      {
        std::lock_guard<std::mutex> lock(rtpPacerMutex_);
        if (rtpPacerStopping_) {
          return;
        }
        if (accessUnit.generation != rtpQueueGeneration_) {
          continue;
        }
      }
      const auto transmitAt = std::chrono::steady_clock::now();
      SendPacedRTPAccessUnit(accessUnit, transmitAt, spread);
    }
  }

  void SendPacedRTPAccessUnit(QueuedRTPAccessUnit &accessUnit,
                              std::chrono::steady_clock::time_point transmitAt,
                              std::chrono::nanoseconds spread) {
    constexpr std::size_t kPacketBatchSize = 32;
    const std::size_t batchCount =
        (accessUnit.packets.size() + kPacketBatchSize - 1) / kPacketBatchSize;
    for (std::size_t batch = 0; batch < batchCount; ++batch) {
      const auto batchAt = batchCount == 1
          ? transmitAt + spread
          : transmitAt + spread * static_cast<std::int64_t>(batch) /
                             static_cast<std::int64_t>(batchCount - 1);
      std::this_thread::sleep_until(batchAt);
      const std::size_t begin = batch * kPacketBatchSize;
      const std::size_t end = std::min(accessUnit.packets.size(), begin + kPacketBatchSize);
      for (std::size_t index = begin; index < end; ++index) {
        SendPacedRTPPacket(accessUnit.packets[index].bytes);
      }
    }
  }

  void SendPacedRTPPacket(std::vector<std::uint8_t> &packet) {
    if (rtpSocket_ < 0 || packet.empty()) {
      return;
    }
    const std::uint16_t sequence = htons(rtpSequence_++);
    std::memcpy(packet.data() + 2, &sequence, sizeof(sequence));
    const ssize_t sent = sendto(rtpSocket_, packet.data(), packet.size(), MSG_NOSIGNAL,
                                reinterpret_cast<const sockaddr *>(&rtpDestination_), sizeof(rtpDestination_));
    if (sent != static_cast<ssize_t>(packet.size())) {
      LogEncoderError(std::string("paced loopback RTP send failed: ") + std::strerror(errno));
    }
  }

  bool StartControlServer() {
    std::error_code error;
    const std::filesystem::path path(controlSocketPath_);
    std::filesystem::create_directories(path.parent_path(), error);
    if (error) {
      gzerr << "xgc_media_camera cannot create control socket directory: " << error.message() << "\n";
      return false;
    }
    if (controlSocketPath_.size() >= sizeof(sockaddr_un::sun_path)) {
      gzerr << "xgc_media_camera control socket path is too long\n";
      return false;
    }
    std::filesystem::remove(path, error);
    controlListener_ = socket(AF_UNIX, SOCK_STREAM | SOCK_CLOEXEC, 0);
    if (controlListener_ < 0) {
      gzerr << "xgc_media_camera cannot create control socket: " << std::strerror(errno) << "\n";
      return false;
    }
    sockaddr_un address{};
    address.sun_family = AF_UNIX;
    std::strncpy(address.sun_path, controlSocketPath_.c_str(), sizeof(address.sun_path) - 1);
    if (bind(controlListener_, reinterpret_cast<const sockaddr *>(&address), sizeof(address)) != 0 ||
        listen(controlListener_, 8) != 0 || chmod(controlSocketPath_.c_str(), 0600) != 0) {
      gzerr << "xgc_media_camera cannot bind control socket " << controlSocketPath_ << ": " << std::strerror(errno) << "\n";
      close(controlListener_);
      controlListener_ = -1;
      std::filesystem::remove(path, error);
      return false;
    }
    controlThread_ = std::thread(&XGCMediaCameraPlugin::ControlLoop, this);
    return true;
  }

  void StopControlServer() {
    stopping_.store(true);
    {
      std::lock_guard<std::mutex> lock(snapshotMutex_);
      if (snapshot_.id.empty()) {
        snapshot_.id = "stopped";
      }
      snapshot_.failed = true;
      snapshot_.completed = true;
      snapshot_.error = "capture source is stopping";
    }
    snapshotCondition_.notify_all();
    if (controlListener_ >= 0) {
      shutdown(controlListener_, SHUT_RDWR);
      close(controlListener_);
      controlListener_ = -1;
    }
    if (controlThread_.joinable()) {
      controlThread_.join();
    }
    std::error_code error;
    if (!controlSocketPath_.empty()) {
      std::filesystem::remove(controlSocketPath_, error);
    }
  }

  void ControlLoop() {
    while (!stopping_.load()) {
      const int client = accept4(controlListener_, nullptr, nullptr, SOCK_CLOEXEC);
      if (client < 0) {
        if (errno == EINTR) {
          continue;
        }
        if (!stopping_.load()) {
          gzwarn << "xgc_media_camera control accept failed: " << std::strerror(errno) << "\n";
        }
        break;
      }
      HandleControlClient(client);
      close(client);
    }
  }

  void HandleControlClient(int client) {
    const auto request = ReadControlLine(client);
    if (!request) {
      return;
    }
    const auto operation = JSONString(*request, "operation");
    if (!operation) {
      ReplyError(client, "operation is required");
      return;
    }
    if (*operation == "set-active") {
      const auto active = JSONBoolean(*request, "active");
      if (!active) {
        ReplyError(client, "active is required");
        return;
      }
      desiredActive_.store(*active);
      if (*active) {
        forceKeyframe_.store(true);
      } else {
        ClearRTPQueue();
      }
      ReplyOK(client);
      return;
    }
    if (*operation == "request-keyframe") {
      forceKeyframe_.store(true);
      ReplyOK(client);
      return;
    }
    if (*operation == "snapshot") {
      const auto snapshotID = JSONString(*request, "snapshotId");
      if (!snapshotID || !IsSafeIdentifier(*snapshotID)) {
        ReplyError(client, "snapshotId must be a stable identifier");
        return;
      }
      HandleSnapshotRequest(client, *snapshotID);
      return;
    }
    ReplyError(client, "unsupported media source operation");
  }

  void ReplyOK(int client) {
    static constexpr char kReply[] = "{\"ok\":true}\n";
    SendAll(client, kReply, sizeof(kReply) - 1);
  }

  void ReplyError(int client, const std::string &message) {
    const std::string reply = "{\"ok\":false,\"error\":\"" + EscapeJSON(message) + "\"}\n";
    SendAll(client, reply.data(), reply.size());
  }

  void HandleSnapshotRequest(int client, const std::string &snapshotID) {
    std::unique_lock<std::mutex> transaction(snapshotTransactionMutex_);
    {
      std::lock_guard<std::mutex> lock(snapshotMutex_);
      snapshot_ = SnapshotResult{};
      snapshot_.id = snapshotID;
      // Capture the first render completed *after* this transaction begins.
      // Gazebo's freshly activated camera target can still contain its
      // zero-filled allocation during the first target callback.
      snapshotRenderPassesToSkip_ = 1;
    }
    forceKeyframe_.store(true);

    SnapshotResult response;
    {
      std::unique_lock<std::mutex> lock(snapshotMutex_);
      const bool ready = snapshotCondition_.wait_for(lock, std::chrono::seconds(4), [this] {
        return snapshot_.completed || stopping_.load();
      });
      if (!ready || !snapshot_.completed || snapshot_.failed) {
        const std::string error =
            !ready ? "snapshot timed out"
                   : snapshot_.error.empty() ? "snapshot failed" : snapshot_.error;
        snapshot_ = SnapshotResult{};
        snapshotRenderPassesToSkip_ = 0;
        ReplyError(client, error);
        return;
      }
      response = std::move(snapshot_);
      snapshot_ = SnapshotResult{};
      snapshotRenderPassesToSkip_ = 0;
    }

    std::ostringstream header;
    header << "{\"ok\":true,\"snapshotId\":\"" << EscapeJSON(response.id)
           << "\",\"frameId\":\"" << EscapeJSON(frameID_)
           // Gazebo's LastMeasurementTime is simulation/source time, not wall
           // clock Unix time. The media edge preserves that clock domain for
           // time matching ROS marker observations during calibration.
           << "\",\"timestampNanoseconds\":" << response.timestampNanoseconds
           << ",\"width\":" << response.width
           << ",\"height\":" << response.height
           << ",\"pixelFormat\":\"rgb8\""
           << ",\"jpegBytes\":" << response.jpeg.size()
           << ",\"rgbBytes\":" << response.rgb.size()
           << ",\"cameraMatrix\":[";
    for (std::size_t index = 0; index < response.cameraMatrix.size(); ++index) {
      if (index != 0) {
        header << ',';
      }
      header << response.cameraMatrix[index];
    }
    header << "],\"distortion\":[";
    for (std::size_t index = 0; index < response.distortion.size(); ++index) {
      if (index != 0) {
        header << ',';
      }
      header << response.distortion[index];
    }
    header << "]}\n";
    const std::string encodedHeader = header.str();
    if (!SendAll(client, encodedHeader.data(), encodedHeader.size()) ||
        !SendAll(client, response.jpeg.data(), response.jpeg.size()) ||
        !SendAll(client, response.rgb.data(), response.rgb.size())) {
      return;
    }
  }

  bool SnapshotPending() const {
    std::lock_guard<std::mutex> lock(snapshotMutex_);
    return !snapshot_.id.empty() && !snapshot_.completed;
  }

  void OnPostRender() {
    if (stopping_.load() || !sensor_) {
      return;
    }
    if (!camera_) {
      camera_ = sensor_->Camera();
      if (!camera_) {
        if (desiredActive_.load() || SnapshotPending()) {
          sensor_->SetActive(true);
        }
        return;
      }
    }
    if (!AttachRenderTargetListener()) {
      return;
    }
    const bool shouldRender = desiredActive_.load() || SnapshotPending();
    if (shouldRender) {
      if (!sensor_->IsActive()) {
        sensor_->SetActive(true);
      }
      return;
    }
    if (encoderResourcesActive_.load()) {
      // Let the render-target listener run one final time while its GL context
      // is current. It releases NVENC/GL resources and the next post-render
      // pass disables the Gazebo sensor completely.
      cleanupEncoderRequested_.store(true);
      if (!sensor_->IsActive()) {
        sensor_->SetActive(true);
      }
      return;
    }
    if (sensor_->IsActive()) {
      sensor_->SetActive(false);
    }
  }

  bool AttachRenderTargetListener() {
    if (renderTarget_) {
      return true;
    }
    if (!camera_ || !camera_->RenderTexture()) {
      return false;
    }
    Ogre::RenderTarget *target = camera_->RenderTexture()->getBuffer()->getRenderTarget();
    if (!target) {
      return false;
    }
    target->addListener(this);
    renderTarget_ = target;
    return true;
  }

  void postRenderTargetUpdate(const Ogre::RenderTargetEvent &) override {
    if (stopping_.load()) {
      return;
    }
    if (cleanupEncoderRequested_.exchange(false) && !desiredActive_.load() && !SnapshotPending()) {
      DestroyEncoder();
      return;
    }
    if (!desiredActive_.load() && !SnapshotPending()) {
      return;
    }
    if (SnapshotPending()) {
      CaptureSnapshot();
    }
    if (!desiredActive_.load()) {
      return;
    }
    if (!EncodeRenderedFrame()) {
      // Keep the source alive; a transient GPU context or driver reset should
      // be visible in Gazebo logs but must not turn into a CPU fallback path.
      return;
    }
  }

  bool CaptureSnapshot() {
    SnapshotResult result;
    {
      std::lock_guard<std::mutex> lock(snapshotMutex_);
      if (snapshot_.id.empty() || snapshot_.completed) {
        return false;
      }
      if (snapshotRenderPassesToSkip_ > 0) {
        --snapshotRenderPassesToSkip_;
        return false;
      }
      result.id = snapshot_.id;
    }
    if (!camera_ || !camera_->RenderTexture()) {
      CompleteSnapshotFailure("camera render texture is unavailable");
      return false;
    }
    const unsigned int width = camera_->ImageWidth();
    const unsigned int height = camera_->ImageHeight();
    if (width == 0 || height == 0 || width > 8192 || height > 8192) {
      CompleteSnapshotFailure("camera dimensions are invalid");
      return false;
    }
    const std::size_t bytes = static_cast<std::size_t>(width) * height * 3;
    result.rgb.resize(bytes);
    try {
      Ogre::PixelBox destination(width, height, 1, Ogre::PF_R8G8B8, result.rgb.data());
      camera_->RenderTexture()->getBuffer()->blitToMemory(destination);
    } catch (const std::exception &error) {
      CompleteSnapshotFailure(std::string("camera snapshot readback failed: ") + error.what());
      return false;
    }
    result.jpeg = EncodeJPEG(result.rgb, width, height);
    if (result.jpeg.empty()) {
      CompleteSnapshotFailure("camera snapshot JPEG encoding failed");
      return false;
    }
    result.width = width;
    result.height = height;
    const double hfov = camera_->HFOV().Radian();
    const double focalLength = static_cast<double>(width) / (2.0 * std::tan(hfov / 2.0));
    result.cameraMatrix = {focalLength, 0.0, (static_cast<double>(width) - 1.0) / 2.0,
                           0.0, focalLength, (static_cast<double>(height) - 1.0) / 2.0,
                           0.0, 0.0, 1.0};
    result.distortion.fill(0.0);
    const common::Time measurementTime = sensor_->LastMeasurementTime();
    result.timestampNanoseconds = static_cast<std::int64_t>(measurementTime.sec) * 1'000'000'000LL + measurementTime.nsec;
    {
      std::lock_guard<std::mutex> lock(snapshotMutex_);
      if (snapshot_.id != result.id || snapshot_.completed) {
        return false;
      }
      result.completed = true;
      snapshot_ = std::move(result);
    }
    snapshotCondition_.notify_all();
    return true;
  }

  void CompleteSnapshotFailure(const std::string &error) {
    {
      std::lock_guard<std::mutex> lock(snapshotMutex_);
      if (snapshot_.id.empty() || snapshot_.completed) {
        return;
      }
      snapshot_.failed = true;
      snapshot_.completed = true;
      snapshot_.error = error;
    }
    snapshotCondition_.notify_all();
  }

  std::vector<std::uint8_t> EncodeJPEG(const std::vector<std::uint8_t> &rgb, unsigned int width, unsigned int height) const {
    jpeg_compress_struct encoder{};
    JPEGErrorManager errors{};
    encoder.err = jpeg_std_error(&errors.manager);
    errors.manager.error_exit = JPEGErrorExit;
    if (setjmp(errors.jumpBuffer) != 0) {
      jpeg_destroy_compress(&encoder);
      return {};
    }
    jpeg_create_compress(&encoder);
    unsigned char *encoded = nullptr;
    unsigned long encodedSize = 0;
    jpeg_mem_dest(&encoder, &encoded, &encodedSize);
    encoder.image_width = width;
    encoder.image_height = height;
    encoder.input_components = 3;
    encoder.in_color_space = JCS_RGB;
    jpeg_set_defaults(&encoder);
    jpeg_set_quality(&encoder, jpegQuality_, TRUE);
    jpeg_start_compress(&encoder, TRUE);
    while (encoder.next_scanline < encoder.image_height) {
      JSAMPROW row = const_cast<JSAMPLE *>(rgb.data() + static_cast<std::size_t>(encoder.next_scanline) * width * 3);
      jpeg_write_scanlines(&encoder, &row, 1);
    }
    jpeg_finish_compress(&encoder);
    std::vector<std::uint8_t> result(encoded, encoded + encodedSize);
    jpeg_destroy_compress(&encoder);
    std::free(encoded);
    return result;
  }

  bool EncodeRenderedFrame() {
    if (!camera_ || !camera_->RenderTexture()) {
      return false;
    }
    auto *renderTexture = dynamic_cast<Ogre::GLTexture *>(camera_->RenderTexture());
    if (!renderTexture || renderTexture->getGLTextureTarget() != GL_TEXTURE_2D) {
      LogEncoderError("Gazebo camera render texture is not a GL_TEXTURE_2D texture");
      return false;
    }
    const unsigned int width = camera_->ImageWidth();
    const unsigned int height = camera_->ImageHeight();
    if (!EnsureEncoder(width, height)) {
      return false;
    }
    if (!CopyTextureToEncoderInput(renderTexture->getGLID(), width, height)) {
      return false;
    }
    NV_ENC_MAP_INPUT_RESOURCE mapping{};
    mapping.version = NV_ENC_MAP_INPUT_RESOURCE_VER;
    mapping.registeredResource = registeredInput_;
    if (api_.nvEncMapInputResource(encoder_, &mapping) != NV_ENC_SUCCESS) {
      LogEncoderError("NVENC could not map the OpenGL input texture");
      return false;
    }
    const bool forceKeyframe = forceKeyframe_.exchange(false);
    NV_ENC_PIC_PARAMS picture{};
    picture.version = NV_ENC_PIC_PARAMS_VER;
    picture.inputWidth = width;
    picture.inputHeight = height;
    picture.inputPitch = width;
    picture.inputBuffer = mapping.mappedResource;
    picture.outputBitstream = bitstream_;
    picture.bufferFmt = mapping.mappedBufferFmt;
    picture.pictureStruct = NV_ENC_PIC_STRUCT_FRAME;
    const double fps = std::max(0.1, static_cast<double>(sensor_->UpdateRate()));
    const std::uint64_t inputTimestamp = static_cast<std::uint64_t>(
        std::llround(static_cast<double>(encodedFrameIndex_) * 90'000.0 / fps));
    picture.inputTimeStamp = inputTimestamp;
    picture.inputDuration = std::max<std::uint64_t>(
        1, static_cast<std::uint64_t>(std::llround(90'000.0 / fps)));
    if (forceKeyframe) {
      picture.encodePicFlags = NV_ENC_PIC_FLAG_FORCEIDR | NV_ENC_PIC_FLAG_OUTPUT_SPSPPS;
    }
    const NVENCSTATUS encodeStatus = api_.nvEncEncodePicture(encoder_, &picture);
    if (encodeStatus != NV_ENC_SUCCESS && encodeStatus != NV_ENC_ERR_NEED_MORE_INPUT) {
      api_.nvEncUnmapInputResource(encoder_, mapping.mappedResource);
      LogEncoderError("NVENC could not encode the OpenGL frame");
      return false;
    }
    bool sent = true;
    if (encodeStatus == NV_ENC_SUCCESS) {
      NV_ENC_LOCK_BITSTREAM locked{};
      locked.version = NV_ENC_LOCK_BITSTREAM_VER;
      locked.outputBitstream = bitstream_;
      if (api_.nvEncLockBitstream(encoder_, &locked) != NV_ENC_SUCCESS) {
        sent = false;
        LogEncoderError("NVENC could not lock the H264 bitstream");
      } else {
        sent = SendH264AccessUnit(
            static_cast<const std::uint8_t *>(locked.bitstreamBufferPtr),
            locked.bitstreamSizeInBytes,
            static_cast<std::uint32_t>(locked.outputTimeStamp));
        api_.nvEncUnlockBitstream(encoder_, bitstream_);
      }
    }
    api_.nvEncUnmapInputResource(encoder_, mapping.mappedResource);
    ++encodedFrameIndex_;
    return sent;
  }

  bool EnsureEncoder(unsigned int width, unsigned int height) {
    if (encoder_ && encoderWidth_ == width && encoderHeight_ == height) {
      return true;
    }
    DestroyEncoder();
    if (width == 0 || height == 0 || !EnsureConversionTexture(width, height)) {
      return false;
    }
    nvencLibrary_ = dlopen("libnvidia-encode.so.1", RTLD_NOW | RTLD_LOCAL);
    if (!nvencLibrary_) {
      LogEncoderError("libnvidia-encode.so.1 is unavailable; no CPU fallback is permitted");
      return false;
    }
    const auto createInstance = reinterpret_cast<NvEncodeAPICreateInstance>(dlsym(nvencLibrary_, "NvEncodeAPICreateInstance"));
    if (!createInstance) {
      LogEncoderError("NvEncodeAPICreateInstance is unavailable");
      DestroyEncoder();
      return false;
    }
    api_ = {};
    api_.version = NV_ENCODE_API_FUNCTION_LIST_VER;
    if (createInstance(&api_) != NV_ENC_SUCCESS || !api_.nvEncOpenEncodeSessionEx || !api_.nvEncInitializeEncoder) {
      LogEncoderError("NVENC API initialization failed");
      DestroyEncoder();
      return false;
    }
    NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS session{};
    session.version = NV_ENC_OPEN_ENCODE_SESSION_EX_PARAMS_VER;
    session.deviceType = NV_ENC_DEVICE_TYPE_OPENGL;
    session.device = nullptr;  // The current GL context owns the device on Linux.
    session.apiVersion = NVENCAPI_VERSION;
    if (api_.nvEncOpenEncodeSessionEx(&session, &encoder_) != NV_ENC_SUCCESS) {
      LogEncoderError("NVENC could not open an OpenGL encode session");
      DestroyEncoder();
      return false;
    }
    NV_ENC_PRESET_CONFIG preset{};
    preset.version = NV_ENC_PRESET_CONFIG_VER;
    preset.presetCfg.version = NV_ENC_CONFIG_VER;
    if (api_.nvEncGetEncodePresetConfig(encoder_, NV_ENC_CODEC_H264_GUID, NV_ENC_PRESET_LOW_LATENCY_HQ_GUID, &preset) != NV_ENC_SUCCESS) {
      LogEncoderError("NVENC low-latency H264 preset is unavailable");
      DestroyEncoder();
      return false;
    }
    const double fps = std::max(0.1, static_cast<double>(sensor_->UpdateRate()));
    const std::uint32_t fpsNumerator = static_cast<std::uint32_t>(std::llround(fps * 1'000.0));
    NV_ENC_CONFIG configuration = preset.presetCfg;
    configuration.version = NV_ENC_CONFIG_VER;
    configuration.profileGUID = NV_ENC_H264_PROFILE_BASELINE_GUID;
    configuration.gopLength = std::max<std::uint32_t>(1, static_cast<std::uint32_t>(std::llround(fps * 2.0)));
    configuration.frameIntervalP = 1;
    configuration.rcParams.version = NV_ENC_RC_PARAMS_VER;
    // WebRTC needs a bounded *average* rate but an IDR legitimately needs
    // more bits than a delta frame. Strict one-frame CBR made every two-second
    // IDR visibly blur at 4K. VBR with an explicit peak, paired with the RTP
    // pacer above, preserves IDR quality without emitting UDP microbursts.
    configuration.rcParams.rateControlMode = NV_ENC_PARAMS_RC_VBR;
    configuration.rcParams.averageBitRate = static_cast<std::uint32_t>(bitrate_);
    configuration.rcParams.maxBitRate = static_cast<std::uint32_t>(maxBitrate_);
    const std::uint64_t vbvBits = static_cast<std::uint64_t>(maxBitrate_) * static_cast<std::uint64_t>(vbvBufferMilliseconds_) / 1'000ULL;
    configuration.rcParams.vbvBufferSize = static_cast<std::uint32_t>(std::min<std::uint64_t>(std::numeric_limits<std::uint32_t>::max(), std::max<std::uint64_t>(1, vbvBits)));
    configuration.rcParams.vbvInitialDelay = configuration.rcParams.vbvBufferSize;
    configuration.rcParams.enableAQ = 1;
    configuration.rcParams.aqStrength = 8;
    configuration.rcParams.strictGOPTarget = 0;
    configuration.encodeCodecConfig.h264Config.repeatSPSPPS = 1;
    configuration.encodeCodecConfig.h264Config.outputAUD = 1;
    configuration.encodeCodecConfig.h264Config.level = NV_ENC_LEVEL_H264_51;
    configuration.encodeCodecConfig.h264Config.idrPeriod = configuration.gopLength;
    configuration.encodeCodecConfig.h264Config.entropyCodingMode = NV_ENC_H264_ENTROPY_CODING_MODE_CAVLC;
    NV_ENC_INITIALIZE_PARAMS initialization{};
    initialization.version = NV_ENC_INITIALIZE_PARAMS_VER;
    initialization.encodeGUID = NV_ENC_CODEC_H264_GUID;
    initialization.presetGUID = NV_ENC_PRESET_LOW_LATENCY_HQ_GUID;
    initialization.encodeWidth = width;
    initialization.encodeHeight = height;
    initialization.darWidth = width;
    initialization.darHeight = height;
    initialization.frameRateNum = std::max<std::uint32_t>(1, fpsNumerator);
    initialization.frameRateDen = 1'000;
    initialization.enableEncodeAsync = 0;
    initialization.enablePTD = 1;
    initialization.encodeConfig = &configuration;
    if (api_.nvEncInitializeEncoder(encoder_, &initialization) != NV_ENC_SUCCESS) {
      LogEncoderError("NVENC could not initialize H264 encoding");
      DestroyEncoder();
      return false;
    }
    NV_ENC_INPUT_RESOURCE_OPENGL_TEX texture{};
    texture.texture = encoderTexture_;
    texture.target = GL_TEXTURE_2D;
    NV_ENC_REGISTER_RESOURCE resource{};
    resource.version = NV_ENC_REGISTER_RESOURCE_VER;
    resource.resourceType = NV_ENC_INPUT_RESOURCE_TYPE_OPENGL_TEX;
    resource.width = width;
    resource.height = height;
    resource.pitch = width * 4;
    resource.resourceToRegister = &texture;
    resource.bufferFormat = NV_ENC_BUFFER_FORMAT_ABGR;
    resource.bufferUsage = NV_ENC_INPUT_IMAGE;
    if (api_.nvEncRegisterResource(encoder_, &resource) != NV_ENC_SUCCESS) {
      LogEncoderError("NVENC could not register the OpenGL texture");
      DestroyEncoder();
      return false;
    }
    registeredInput_ = resource.registeredResource;
    NV_ENC_CREATE_BITSTREAM_BUFFER bitstream{};
    bitstream.version = NV_ENC_CREATE_BITSTREAM_BUFFER_VER;
    if (api_.nvEncCreateBitstreamBuffer(encoder_, &bitstream) != NV_ENC_SUCCESS) {
      LogEncoderError("NVENC could not allocate an H264 bitstream buffer");
      DestroyEncoder();
      return false;
    }
    bitstream_ = bitstream.bitstreamBuffer;
    encoderWidth_ = width;
    encoderHeight_ = height;
    encodedFrameIndex_ = 0;
    forceKeyframe_.store(true);
    encoderResourcesActive_.store(true);
    return true;
  }

  bool EnsureConversionTexture(unsigned int width, unsigned int height) {
    if (!glewInitialized_) {
      // SensorManager invokes its global post-render event after it releases
      // the OGRE context. RenderTargetListener, in contrast, runs inside the
      // target update with that context current, which is the only safe place
      // to initialize the plugin's GLEW dispatch table.
      glGetError();
      if (glewInit() != GLEW_OK) {
        LogEncoderError("GLEW could not initialize in the Gazebo render context");
        return false;
      }
      glGetError();
      glewInitialized_ = true;
    }
    if (encoderTexture_ != 0 && encoderTextureWidth_ == width && encoderTextureHeight_ == height) {
      return true;
    }
    DestroyConversionTexture();
    glGenTextures(1, &encoderTexture_);
    glBindTexture(GL_TEXTURE_2D, encoderTexture_);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_NEAREST);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
    glTexParameteri(GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
    glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA8, width, height, 0, GL_RGBA, GL_UNSIGNED_BYTE, nullptr);
    glBindTexture(GL_TEXTURE_2D, 0);
    glGenFramebuffers(1, &readFramebuffer_);
    glGenFramebuffers(1, &drawFramebuffer_);
    if (encoderTexture_ == 0 || readFramebuffer_ == 0 || drawFramebuffer_ == 0 || glGetError() != GL_NO_ERROR) {
      LogEncoderError("OpenGL could not allocate the GPU-only NVENC conversion texture");
      DestroyConversionTexture();
      return false;
    }
    encoderTextureWidth_ = width;
    encoderTextureHeight_ = height;
    return true;
  }

  bool CopyTextureToEncoderInput(GLuint sourceTexture, unsigned int width, unsigned int height) {
    glBindFramebuffer(GL_READ_FRAMEBUFFER, readFramebuffer_);
    glFramebufferTexture2D(GL_READ_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, sourceTexture, 0);
    glBindFramebuffer(GL_DRAW_FRAMEBUFFER, drawFramebuffer_);
    glFramebufferTexture2D(GL_DRAW_FRAMEBUFFER, GL_COLOR_ATTACHMENT0, GL_TEXTURE_2D, encoderTexture_, 0);
    if (glCheckFramebufferStatus(GL_READ_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE ||
        glCheckFramebufferStatus(GL_DRAW_FRAMEBUFFER) != GL_FRAMEBUFFER_COMPLETE) {
      glBindFramebuffer(GL_FRAMEBUFFER, 0);
      LogEncoderError("OpenGL could not bind Gazebo and NVENC conversion framebuffers");
      return false;
    }
    // The source and destination stay entirely on the GPU. GL's framebuffer
    // coordinate convention also keeps this copy aligned with the OGRE pixel
    // readback used by the snapshot transaction.
    glBlitFramebuffer(0, 0, width, height, 0, 0, width, height, GL_COLOR_BUFFER_BIT, GL_NEAREST);
    glBindFramebuffer(GL_FRAMEBUFFER, 0);
    glFlush();
    if (glGetError() != GL_NO_ERROR) {
      LogEncoderError("OpenGL GPU texture copy for NVENC failed");
      return false;
    }
    return true;
  }

  void DestroyEncoder() {
    if (encoder_) {
      if (registeredInput_ && api_.nvEncUnregisterResource) {
        api_.nvEncUnregisterResource(encoder_, registeredInput_);
      }
      registeredInput_ = nullptr;
      if (bitstream_ && api_.nvEncDestroyBitstreamBuffer) {
        api_.nvEncDestroyBitstreamBuffer(encoder_, bitstream_);
      }
      bitstream_ = nullptr;
      if (api_.nvEncDestroyEncoder) {
        api_.nvEncDestroyEncoder(encoder_);
      }
      encoder_ = nullptr;
    }
    api_ = {};
    if (nvencLibrary_) {
      dlclose(nvencLibrary_);
      nvencLibrary_ = nullptr;
    }
    encoderWidth_ = 0;
    encoderHeight_ = 0;
    encoderResourcesActive_.store(false);
    DestroyConversionTexture();
  }

  void DestroyConversionTexture() {
    if (readFramebuffer_ != 0) {
      glDeleteFramebuffers(1, &readFramebuffer_);
      readFramebuffer_ = 0;
    }
    if (drawFramebuffer_ != 0) {
      glDeleteFramebuffers(1, &drawFramebuffer_);
      drawFramebuffer_ = 0;
    }
    if (encoderTexture_ != 0) {
      glDeleteTextures(1, &encoderTexture_);
      encoderTexture_ = 0;
    }
    encoderTextureWidth_ = 0;
    encoderTextureHeight_ = 0;
  }

  bool SendH264AccessUnit(const std::uint8_t *data, std::size_t size, std::uint32_t timestamp) {
    if (!data || size == 0 || rtpSocket_ < 0) {
      return false;
    }
    const auto nalUnits = SplitAnnexB(data, size);
    if (nalUnits.empty()) {
      LogEncoderError("NVENC produced a non-Annex-B H264 access unit");
      return false;
    }
    std::vector<QueuedRTPPacket> packets;
    bool keyframe = false;
    for (std::size_t index = 0; index < nalUnits.size(); ++index) {
      const auto &nal = nalUnits[index];
      if (nal.empty()) {
        continue;
      }
      keyframe = keyframe || (nal.front() & 0x1f) == 5;
      const bool lastNAL = index + 1 == nalUnits.size();
      if (nal.size() <= kMaximumRtpPayloadBytes) {
        if (!AppendRTPPacket(packets, nal.data(), nal.size(), timestamp, lastNAL)) {
          return false;
        }
        continue;
      }
      const std::uint8_t nalHeader = nal.front();
      const std::uint8_t fuIndicator = static_cast<std::uint8_t>((nalHeader & 0xe0) | 28);
      const std::uint8_t nalType = static_cast<std::uint8_t>(nalHeader & 0x1f);
      std::size_t offset = 1;
      const std::size_t fragmentPayload = kMaximumRtpPayloadBytes - 2;
      bool first = true;
      while (offset < nal.size()) {
        const std::size_t count = std::min(fragmentPayload, nal.size() - offset);
        const bool last = offset + count == nal.size();
        std::vector<std::uint8_t> fragment;
        fragment.reserve(count + 2);
        fragment.push_back(fuIndicator);
        fragment.push_back(static_cast<std::uint8_t>(nalType | (first ? 0x80 : 0) | (last ? 0x40 : 0)));
        fragment.insert(fragment.end(), nal.begin() + static_cast<std::ptrdiff_t>(offset),
                        nal.begin() + static_cast<std::ptrdiff_t>(offset + count));
        if (!AppendRTPPacket(packets, fragment.data(), fragment.size(), timestamp, lastNAL && last)) {
          return false;
        }
        offset += count;
        first = false;
      }
    }
    return EnqueueRTPAccessUnit(std::move(packets), keyframe);
  }

  bool AppendRTPPacket(std::vector<QueuedRTPPacket> &packets, const std::uint8_t *payload,
                       std::size_t payloadSize, std::uint32_t timestamp, bool marker) {
    if (!payload || payloadSize == 0 || payloadSize > kMaximumRtpPayloadBytes) {
      return false;
    }
    QueuedRTPPacket packet;
    packet.bytes.resize(12 + payloadSize);
    packet.bytes[0] = 0x80;
    packet.bytes[1] = static_cast<std::uint8_t>(kH264PayloadType | (marker ? 0x80 : 0));
    const std::uint32_t networkTimestamp = htonl(timestamp);
    const std::uint32_t ssrc = htonl(kRtpSSRC);
    std::memcpy(packet.bytes.data() + 4, &networkTimestamp, sizeof(networkTimestamp));
    std::memcpy(packet.bytes.data() + 8, &ssrc, sizeof(ssrc));
    std::memcpy(packet.bytes.data() + 12, payload, payloadSize);
    packets.push_back(std::move(packet));
    return true;
  }

  void LogEncoderError(const std::string &message) {
    std::lock_guard<std::mutex> lock(encoderLogMutex_);
    const auto now = std::chrono::steady_clock::now();
    if (message != lastEncoderError_ || now - lastEncoderErrorAt_ > std::chrono::seconds(5)) {
      gzwarn << "xgc_media_camera: " << message << "\n";
      lastEncoderError_ = message;
      lastEncoderErrorAt_ = now;
    }
  }

  sensors::CameraSensorPtr sensor_;
  rendering::CameraPtr camera_;
  event::ConnectionPtr postRenderConnection_;
  Ogre::RenderTarget *renderTarget_ = nullptr;

  std::string sourceID_;
  std::string frameID_;
  std::string rtpHost_;
  int rtpPort_ = 0;
  std::string controlSocketPath_;
  int bitrate_ = 0;
  int maxBitrate_ = 0;
  int pacingBitrate_ = 0;
  int vbvBufferMilliseconds_ = 500;
  int jpegQuality_ = 90;

  std::atomic<bool> stopping_{false};
  std::atomic<bool> desiredActive_{false};
  std::atomic<bool> forceKeyframe_{true};
  std::atomic<bool> cleanupEncoderRequested_{false};
  std::atomic<bool> encoderResourcesActive_{false};
  int controlListener_ = -1;
  std::thread controlThread_;
  std::mutex snapshotTransactionMutex_;
  mutable std::mutex snapshotMutex_;
  std::condition_variable snapshotCondition_;
  SnapshotResult snapshot_;
  unsigned int snapshotRenderPassesToSkip_ = 0;

  int rtpSocket_ = -1;
  sockaddr_in rtpDestination_{};
  std::uint16_t rtpSequence_ = 0;
  std::mutex rtpPacerMutex_;
  std::condition_variable rtpPacerCondition_;
  std::deque<QueuedRTPAccessUnit> rtpQueue_;
  std::thread rtpPacerThread_;
  bool rtpPacerStopping_ = false;
  std::size_t rtpQueuedBytes_ = 0;
  std::uint64_t rtpQueueGeneration_ = 0;

  void *nvencLibrary_ = nullptr;
  NV_ENCODE_API_FUNCTION_LIST api_{};
  void *encoder_ = nullptr;
  NV_ENC_REGISTERED_PTR registeredInput_ = nullptr;
  NV_ENC_OUTPUT_PTR bitstream_ = nullptr;
  GLuint encoderTexture_ = 0;
  GLuint readFramebuffer_ = 0;
  GLuint drawFramebuffer_ = 0;
  unsigned int encoderTextureWidth_ = 0;
  unsigned int encoderTextureHeight_ = 0;
  unsigned int encoderWidth_ = 0;
  unsigned int encoderHeight_ = 0;
  std::uint64_t encodedFrameIndex_ = 0;
  bool glewInitialized_ = false;

  std::mutex encoderLogMutex_;
  std::string lastEncoderError_;
  std::chrono::steady_clock::time_point lastEncoderErrorAt_{};
};

GZ_REGISTER_SENSOR_PLUGIN(XGCMediaCameraPlugin)

}  // namespace gazebo
